// CineVerse Mock Database with Direct Native Streaming Links & Episode Lists
window.cineVerseData = {
  movies: [
    {
      id: "m-cyberpunk-2099",
      title: "Cyberpunk 2099: Neo-Neon",
      type: "movie",
      rating: 8.9,
      year: 2024,
      genres: ["Sci-Fi", "Action"],
      duration: "2h 15m",
      description: "In the sprawling mega-city of Neo-Neon, a cybernetically enhanced mercenary uncovers a corporate conspiracy that threatens to rewrite human consciousness. As lines blur between humanity and machine, they must navigate the neon-drenched underworld to save what remains of the digital frontier.",
      poster: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4", // Sci-Fi open movie
      cast: ["Kai Jensen (Mercenary)", "Dr. Evelyn Vance (Cyberneticist)", "Jaxon Frost (Fixer)"],
      trending: true,
      popular: true
    },
    {
      id: "m-interstellar-voyage",
      title: "Interstellar Voyage",
      type: "movie",
      rating: 9.2,
      year: 2022,
      genres: ["Sci-Fi", "Adventure"],
      duration: "2h 49m",
      description: "When humanity's last crop fields are ravaged by blight, a team of pioneering astronauts embarks on a desperate mission through a newly discovered wormhole. Seeking a habitable world across the stars, they face cosmic anomalies, temporal shifts, and the crushing weight of isolation.",
      poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4", // Fantasy/Space open movie
      cast: ["Commander John Miller", "Dr. Amelia Brand", "TARS (AI Support)"],
      trending: true,
      popular: true
    },
    {
      id: "m-whispering-forest",
      title: "The Whispering Forest",
      type: "movie",
      rating: 7.8,
      year: 2023,
      genres: ["Horror", "Fantasy"],
      duration: "1h 48m",
      description: "A group of researchers enters an ancient forest that is omitted from modern maps. They soon discover that the trees hold memories of the past—and they do not tolerate intruders. Survival becomes a race against the setting sun and the shifting shadows of the woods.",
      poster: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1511497584788-876760111969?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      cast: ["Sarah Jenkins (Botanist)", "Liam O'Connor (Guide)", "Dr. Marcus Thorne (Historian)"],
      trending: false,
      popular: true
    },
    {
      id: "m-love-in-paris",
      title: "Love in Paris",
      type: "movie",
      rating: 7.2,
      year: 2025,
      genres: ["Romance", "Comedy"],
      duration: "1h 55m",
      description: "An introverted travel writer and a spontaneous street artist repeatedly cross paths in the romantic corridors of Paris. As they share their perspectives on life and art over a single week, they must decide if their connection is worth altering the course of their separate futures.",
      poster: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1499856138863-7a626d7ee7ad?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
      cast: ["Chloe Dubois (Writer)", "Lucas Moreau (Artist)", "Sophie (Chloe's Friend)"],
      trending: false,
      popular: true
    },
    {
      id: "m-shadow-assassin",
      title: "Shadow Assassin",
      type: "movie",
      rating: 8.1,
      year: 2024,
      genres: ["Action"],
      duration: "2h 02m",
      description: "Betrayed by the very syndicate that raised him, a legendary assassin goes rogue. Armed with specialized cloaking technology and lethal martial arts expertise, he wages a one-man war against a criminal empire spanning Tokyo, London, and New York.",
      poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      cast: ["Kenji/Zero (Assassin)", "Reiko (Syndicate Leader)", "Agent Vance (Interpol)"],
      trending: true,
      popular: false
    },
    {
      id: "m-laugh-out-loud",
      title: "Laugh Out Loud",
      type: "movie",
      rating: 6.9,
      year: 2023,
      genres: ["Comedy"],
      duration: "1h 35m",
      description: "When three estranged high school friends accidentally hijack a luxury yacht, their weekend escape turns into a chaotic survival comedy on the high seas. Pursued by clueless coast guards and eccentric luxury owners, they learn the true value of friendship and maritime law.",
      poster: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
      cast: ["Tommy (The Plan)", "Buster (The Driver)", "Garry (The Hostage)"],
      trending: false,
      popular: false
    },
    {
      id: "m-midnight-echoes",
      title: "Midnight Echoes",
      type: "movie",
      rating: 7.5,
      year: 2024,
      genres: ["Horror"],
      duration: "1h 50m",
      description: "An investigative podcast host rents a notorious, isolated lighthouse to record their season finale. As midnight approaches, the radio equipment starts capturing voices from ships lost a century ago, and the lighthouse beam begins pointing inland.",
      poster: "https://images.unsplash.com/photo-1508349937151-22b68b72d5b1?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
      cast: ["Diana Vance (Podcaster)", "Old Man Silas (Lighthouse Keeper)", "The Entity"],
      trending: true,
      popular: false
    },
    {
      id: "m-chrono-trigger",
      title: "Chrono Trigger: Paradox",
      type: "movie",
      rating: 8.5,
      year: 2025,
      genres: ["Sci-Fi", "Action"],
      duration: "2h 10m",
      description: "A brilliant physicist creates a temporal stabilizer, only to watch her future self break into the lab to destroy it. Forced into a chase across historical eras and dystopian futures, she must figure out what went wrong before the timeline completely collapses.",
      poster: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
      cast: ["Dr. Claire Bennett", "Claire Bennett (Old)", "Agent Miller (Time Patrol)"],
      trending: false,
      popular: false
    }
  ],
  anime: [
    {
      id: "a-attack-on-titan",
      title: "Attack on Titan",
      type: "anime",
      rating: 9.1,
      year: 2013,
      genres: ["Action", "Fantasy"],
      episodes: "87 Episodes",
      description: "For a century, humanity lived inside massive walls, safe from the man-eating giants known as Titans. But when a colossal Titan breaches the outer wall, Eren Yeager witnesses his home destroyed and his mother devoured. Swearing absolute vengeance, Eren enlists in the Scout Regiment to reclaim the world outside.",
      poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1600&auto=format&fit=crop&q=80",
      cast: ["Eren Yeager", "Mikasa Ackerman", "Armin Arlert", "Levi Ackerman"],
      trending: true,
      popular: true,
      epList: [
        { epNum: 1, title: "To You, in 2000 Years: The Fall of Shiganshina, Part 1", duration: "24m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" },
        { epNum: 2, title: "That Day: The Fall of Shiganshina, Part 2", duration: "23m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" },
        { epNum: 3, title: "A Dim Light Amid Despair: Humanity's Comeback, Part 1", duration: "24m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4" },
        { epNum: 4, title: "The Night of the Disbanding Ceremony: Humanity's Comeback, Part 2", duration: "25m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4" }
      ]
    },
    {
      id: "a-naruto-shippuden",
      title: "Naruto Shippuden",
      type: "anime",
      rating: 8.7,
      year: 2007,
      genres: ["Action", "Adventure"],
      episodes: "500 Episodes",
      description: "After training with Jiraiya for two and a half years, Naruto Uzumaki returns to the Hidden Leaf Village. Stronger and more determined, he faces off against the rogue ninja organization Akatsuki, while continuing his desperate quest to rescue his friend Sasuke Uchiha from the dark paths of Orochimaru.",
      poster: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1600&auto=format&fit=crop&q=80",
      cast: ["Naruto Uzumaki", "Sasuke Uchiha", "Sakura Haruno", "Kakashi Hatake"],
      trending: true,
      popular: true,
      epList: [
        { epNum: 1, title: "Homecoming", duration: "23m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4" },
        { epNum: 2, title: "The Akatsuki Makes Its Move", duration: "24m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4" },
        { epNum: 3, title: "The Results of Training", duration: "23m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4" }
      ]
    },
    {
      id: "a-demon-slayer",
      title: "Demon Slayer: Kimetsu no Yaiba",
      type: "anime",
      rating: 8.8,
      year: 2019,
      genres: ["Action", "Fantasy"],
      episodes: "44 Episodes",
      description: "Tanjiro Kamado's life is shattered when a demon slaughters his family and turns his younger sister, Nezuko, into a demon. Driven by grief and hope, Tanjiro joins the Demon Slayer Corps to find a cure for Nezuko and avenge his family's deaths under the guidance of the legendary Hashira.",
      poster: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&auto=format&fit=crop&q=80",
      cast: ["Tanjiro Kamado", "Nezuko Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira"],
      trending: true,
      popular: true,
      epList: [
        { epNum: 1, title: "Cruelty", duration: "23m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4" },
        { epNum: 2, title: "Trainer Sakonji Urokodaki", duration: "24m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" },
        { epNum: 3, title: "Sabito and Makomo", duration: "23m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" }
      ]
    },
    {
      id: "a-your-name",
      title: "Your Name.",
      type: "anime",
      rating: 8.4,
      year: 2016,
      genres: ["Romance", "Fantasy"],
      episodes: "Movie (1h 46m)",
      description: "Mitsuha, a high school girl in a rural mountain town, wishes to live as a boy in Tokyo. Taki, a high school boy in Tokyo, balances his busy life with art and work. When a comet approaches Earth, they inexplicably begin swapping bodies in their sleep, leaving messages to navigate each other's lives and forge a cosmic bond.",
      poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
      cast: ["Taki Tachibana", "Mitsuha Miyamizu", "Miki Okudera"],
      trending: false,
      popular: true
    },
    {
      id: "a-frieren",
      title: "Frieren: Beyond Journey's End",
      type: "anime",
      rating: 9.3,
      year: 2023,
      genres: ["Fantasy", "Adventure"],
      episodes: "28 Episodes",
      description: "Elf mage Frieren and her courageous companions have defeated the Demon King, bringing peace to the land. As an elf with a lifespan of thousands of years, Frieren watches her human friends age and pass away. Regretting the short time she spent understanding them, she embarks on a new journey to learn more about humanity.",
      poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&auto=format&fit=crop&q=80",
      cast: ["Frieren", "Fern", "Stark", "Himmel"],
      trending: true,
      popular: true,
      epList: [
        { epNum: 1, title: "The Journey's End", duration: "25m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4" },
        { epNum: 2, title: "It Didn't Have to Be Magic", duration: "24m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" },
        { epNum: 3, title: "Blue Moon Weed", duration: "24m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4" }
      ]
    },
    {
      id: "a-jujutsu-kaisen",
      title: "Jujutsu Kaisen",
      type: "anime",
      rating: 8.6,
      year: 2020,
      genres: ["Action", "Fantasy"],
      episodes: "47 Episodes",
      description: "Yuji Itadori, a high schooler with incredible physical strength, swallows a cursed finger of the legendary demon Ryomen Sukuna to save his classmates. Possessed by Sukuna, Yuji is admitted to the Tokyo Jujutsu High School, joining a hidden society of Sorcerers who exorcise malevolent Curses.",
      poster: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1563089145-599997674d42?w=1600&auto=format&fit=crop&q=80",
      cast: ["Yuji Itadori", "Megumi Fushiguro", "Nobara Kugisaki", "Satoru Gojo"],
      trending: false,
      popular: false,
      epList: [
        { epNum: 1, title: "Ryomen Sukuna", duration: "23m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" },
        { epNum: 2, title: "For Myself", duration: "24m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4" }
      ]
    },
    {
      id: "a-spirited-away",
      title: "Spirited Away",
      type: "anime",
      rating: 8.6,
      year: 2001,
      genres: ["Fantasy", "Adventure"],
      episodes: "Movie (2h 05m)",
      description: "While moving to a new neighborhood, 10-year-old Chihiro and her parents wander into what appears to be an abandoned theme park. When her parents undergo a beastly transformation, Chihiro enters the spirit world to work at a bathhouse run by the witch Yubaba, hoping to save her parents and return to the human realm.",
      poster: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=1600&auto=format&fit=crop&q=80",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      cast: ["Chihiro / Sen", "Haku", "Yubaba", "No-Face"],
      trending: false,
      popular: true
    },
    {
      id: "a-evangelion",
      title: "Neon Genesis Evangelion",
      type: "anime",
      rating: 8.5,
      year: 1995,
      genres: ["Sci-Fi", "Action"],
      episodes: "26 Episodes",
      description: "Fifteen years after a global cataclysm known as the Second Impact, teenage boy Shinji Ikari is summoned to Tokyo-3 by his cold father, Gendo, director of NERV. Shinji is coerced into piloting the giant biomechanical Evangelion Unit-01 to defend humanity against cataclysmic beings known as Angels.",
      poster: "https://images.unsplash.com/photo-1563089145-599997674d42?w=500&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
      cast: ["Shinji Ikari", "Rei Ayanami", "Asuka Langley Soryu", "Misato Katsuragi"],
      trending: false,
      popular: false,
      epList: [
        { epNum: 1, title: "Angel Attack", duration: "24m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4" },
        { epNum: 2, title: "The Beast", duration: "23m", videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" }
      ]
    }
  ]
};
